### PR TITLE
I add an alt attribute to the logo image and also improved the color …

### PR DESCRIPTION
**Pull request by gladysgodwin**
…of text to make it accessible and gentle to the eyes

what this PR does?

It added an alt text to the `index.html` file of this folder and also added color to the #h2 text and .lead class so as to improve the ui of the app

### CODE REVIEW

**Review by BolajiAyodeji — CHANGES_REQUESTED** [review]
Hi @gladysgodwin, thanks for this PR!

Someone else in #20 is already working on the color contrast ratio. Can you stick this PR to just the alt text, please?

**Comment by gladysgodwin** [comment]
@BolajiAyodeji Okay I'll stick to the alt attribute only

**Review by gladysgodwin — COMMENTED** [review]
I just updated the changes you requested @BolajiAyodeji

**Review by BolajiAyodeji — APPROVED** [review]
Thanks for this PR!

**Pull request merged**
